/**
 * Titanic Passenger Dataset
 * Compiled historical passenger data with key demographic, socioeconomic, and survival attributes.
 */

const TITANIC_DATASET = [
  { id: 1, name: "Braund, Mr. Owen Harris", pclass: 3, sex: "male", age: 22, sibsp: 1, parch: 0, fare: 7.25, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 2, name: "Cumings, Mrs. John Bradley (Florence Briggs Thayer)", pclass: 1, sex: "female", age: 38, sibsp: 1, parch: 0, fare: 71.2833, embarked: "C", cabin: "C85", deck: "C", survived: 1 },
  { id: 3, name: "Heikkinen, Miss. Laina", pclass: 3, sex: "female", age: 26, sibsp: 0, parch: 0, fare: 7.925, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 4, name: "Futrelle, Mrs. Jacques Heath (Lily May Peel)", pclass: 1, sex: "female", age: 35, sibsp: 1, parch: 0, fare: 53.1, embarked: "S", cabin: "C123", deck: "C", survived: 1 },
  { id: 5, name: "Allen, Mr. William Henry", pclass: 3, sex: "male", age: 35, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 6, name: "Moran, Mr. James", pclass: 3, sex: "male", age: 27, sibsp: 0, parch: 0, fare: 8.4583, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 7, name: "McCarthy, Mr. Timothy J", pclass: 1, sex: "male", age: 54, sibsp: 0, parch: 0, fare: 51.8625, embarked: "S", cabin: "E46", deck: "E", survived: 0 },
  { id: 8, name: "Palsson, Master. Gosta Leonard", pclass: 3, sex: "male", age: 2, sibsp: 3, parch: 1, fare: 21.075, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 9, name: "Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)", pclass: 3, sex: "female", age: 27, sibsp: 0, parch: 2, fare: 11.1333, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 10, name: "Nasser, Mrs. Nicholas (Adele Achem)", pclass: 2, sex: "female", age: 14, sibsp: 1, parch: 0, fare: 30.0708, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 11, name: "Sandstrom, Miss. Marguerite Rut", pclass: 3, sex: "female", age: 4, sibsp: 1, parch: 1, fare: 16.7, embarked: "S", cabin: "G6", deck: "G", survived: 1 },
  { id: 12, name: "Bonnell, Miss. Elizabeth", pclass: 1, sex: "female", age: 58, sibsp: 0, parch: 0, fare: 26.55, embarked: "S", cabin: "C103", deck: "C", survived: 1 },
  { id: 13, name: "Saundercock, Mr. William Henry", pclass: 3, sex: "male", age: 20, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 14, name: "Andersson, Mr. Anders Johan", pclass: 3, sex: "male", age: 39, sibsp: 1, parch: 5, fare: 31.275, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 15, name: "Vestrom, Miss. Hulda Amanda Adolfina", pclass: 3, sex: "female", age: 14, sibsp: 0, parch: 0, fare: 7.8542, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 16, name: "Hewlett, Mrs. (Mary D Kingcome)", pclass: 2, sex: "female", age: 55, sibsp: 0, parch: 0, fare: 16, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 17, name: "Rice, Master. Eugene", pclass: 3, sex: "male", age: 2, sibsp: 4, parch: 1, fare: 29.125, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 18, name: "Williams, Mr. Charles Eugene", pclass: 2, sex: "male", age: 30, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 19, name: "Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)", pclass: 3, sex: "female", age: 31, sibsp: 1, parch: 0, fare: 18, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 20, name: "Masselmani, Mrs. Fatima", pclass: 3, sex: "female", age: 22, sibsp: 0, parch: 0, fare: 7.225, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 21, name: "Fynney, Mr. Joseph J", pclass: 2, sex: "male", age: 35, sibsp: 0, parch: 0, fare: 26, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 22, name: "Beesley, Mr. Lawrence", pclass: 2, sex: "male", age: 34, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "D56", deck: "D", survived: 1 },
  { id: 23, name: "McGowan, Miss. Anna Anna", pclass: 3, sex: "female", age: 15, sibsp: 0, parch: 0, fare: 8.0292, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 24, name: "Sloper, Mr. William Thompson", pclass: 1, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 35.5, embarked: "S", cabin: "A6", deck: "A", survived: 1 },
  { id: 25, name: "Palsson, Miss. Torborg Danira", pclass: 3, sex: "female", age: 8, sibsp: 3, parch: 1, fare: 21.075, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 26, name: "Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)", pclass: 3, sex: "female", age: 38, sibsp: 1, parch: 5, fare: 31.3875, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 27, name: "Emir, Mr. Farred Chehab", pclass: 3, sex: "male", age: 25, sibsp: 0, parch: 0, fare: 7.225, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 28, name: "Fortune, Mr. Charles Alexander", pclass: 1, sex: "male", age: 19, sibsp: 3, parch: 2, fare: 263, embarked: "S", cabin: "C23 C25 C27", deck: "C", survived: 0 },
  { id: 29, name: "O'Dwyer, Miss. Ellen Nellie", pclass: 3, sex: "female", age: 22, sibsp: 0, parch: 0, fare: 7.8792, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 30, name: "Todoroff, Mr. Lalio", pclass: 3, sex: "male", age: 23, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 31, name: "Uruchurtu, Don. Manuel E", pclass: 1, sex: "male", age: 40, sibsp: 0, parch: 0, fare: 27.7208, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 32, name: "Spencer, Mrs. William Augustus (Marie Eugenie)", pclass: 1, sex: "female", age: 45, sibsp: 1, parch: 0, fare: 146.5208, embarked: "C", cabin: "B78", deck: "B", survived: 1 },
  { id: 33, name: "Glynn, Miss. Mary Agatha", pclass: 3, sex: "female", age: 19, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 34, name: "Wheadon, Mr. Edward H", pclass: 2, sex: "male", age: 66, sibsp: 0, parch: 0, fare: 10.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 35, name: "Meyer, Mr. Edgar Joseph", pclass: 1, sex: "male", age: 28, sibsp: 1, parch: 0, fare: 82.1708, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 36, name: "Holverson, Mr. Alexander Oskar", pclass: 1, sex: "male", age: 42, sibsp: 1, parch: 0, fare: 52, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 37, name: "Mamee, Mr. Hanna", pclass: 3, sex: "male", age: 24, sibsp: 0, parch: 0, fare: 7.2292, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 38, name: "Cann, Mr. Ernest Charles", pclass: 3, sex: "male", age: 21, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 39, name: "Vander Planke, Miss. Augusta Maria", pclass: 3, sex: "female", age: 18, sibsp: 2, parch: 0, fare: 18, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 40, name: "Nicola-Muff, Miss. Jamila", pclass: 3, sex: "female", age: 14, sibsp: 1, parch: 0, fare: 11.2417, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 41, name: "Ahlin, Mrs. Johan (Johanna Persdotter Larsson)", pclass: 3, sex: "female", age: 40, sibsp: 1, parch: 0, fare: 9.475, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 42, name: "Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)", pclass: 2, sex: "female", age: 27, sibsp: 1, parch: 0, fare: 21, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 43, name: "Kraeff, Mr. Theodor", pclass: 3, sex: "male", age: 29, sibsp: 0, parch: 0, fare: 7.8958, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 44, name: "Laroche, Miss. Simonne Marie Anne Andree", pclass: 2, sex: "female", age: 3, sibsp: 1, parch: 2, fare: 41.5792, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 45, name: "Devaney, Miss. Margaret Delia", pclass: 3, sex: "female", age: 19, sibsp: 0, parch: 0, fare: 7.8792, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 46, name: "Rogers, Mr. William John", pclass: 3, sex: "male", age: 30, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 47, name: "Lennon, Mr. Denis", pclass: 3, sex: "male", age: 26, sibsp: 1, parch: 0, fare: 15.5, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 48, name: "O'Driscoll, Miss. Bridget", pclass: 3, sex: "female", age: 24, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 49, name: "Samaan, Mr. Youssef", pclass: 3, sex: "male", age: 28, sibsp: 2, parch: 0, fare: 21.6792, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 50, name: "Arnold-Franchi, Mrs. Josef (Josefine Franchi)", pclass: 3, sex: "female", age: 18, sibsp: 1, parch: 0, fare: 17.8, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 51, name: "Panula, Master. Juha Niilo", pclass: 3, sex: "male", age: 7, sibsp: 4, parch: 1, fare: 31.275, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 52, name: "Nosworthy, Mr. Richard Cater", pclass: 3, sex: "male", age: 21, sibsp: 0, parch: 0, fare: 7.8, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 53, name: "Harper, Mrs. Henry Sleeper (Myna Haxtun)", pclass: 1, sex: "female", age: 49, sibsp: 1, parch: 0, fare: 76.7292, embarked: "C", cabin: "D33", deck: "D", survived: 1 },
  { id: 54, name: "Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)", pclass: 2, sex: "female", age: 29, sibsp: 1, parch: 0, fare: 26, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 55, name: "Ostby, Mr. Engelhart Cornelius", pclass: 1, sex: "male", age: 65, sibsp: 0, parch: 1, fare: 61.9792, embarked: "C", cabin: "B30", deck: "B", survived: 0 },
  { id: 56, name: "Woolner, Mr. Hugh", pclass: 1, sex: "male", age: 46, sibsp: 0, parch: 0, fare: 35.5, embarked: "S", cabin: "C52", deck: "C", survived: 1 },
  { id: 57, name: "Rugg, Miss. Emily", pclass: 2, sex: "female", age: 21, sibsp: 0, parch: 0, fare: 10.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 58, name: "Novel, Mr. Mansouer", pclass: 3, sex: "male", age: 28.5, sibsp: 0, parch: 0, fare: 7.2292, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 59, name: "West, Miss. Constance Mirium", pclass: 2, sex: "female", age: 5, sibsp: 1, parch: 2, fare: 27.75, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 60, name: "Goodwin, Master. William Frederick", pclass: 3, sex: "male", age: 11, sibsp: 5, parch: 2, fare: 46.9, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 61, name: "Sirayanian, Mr. Orsen", pclass: 3, sex: "male", age: 22, sibsp: 0, parch: 0, fare: 7.2292, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 62, name: "Icard, Miss. Amelie", pclass: 1, sex: "female", age: 38, sibsp: 0, parch: 0, fare: 80, embarked: "S", cabin: "B28", deck: "B", survived: 1 },
  { id: 63, name: "Harris, Mr. Henry Birkhardt", pclass: 1, sex: "male", age: 45, sibsp: 1, parch: 0, fare: 83.475, embarked: "S", cabin: "C83", deck: "C", survived: 0 },
  { id: 64, name: "Skoog, Master. Harald", pclass: 3, sex: "male", age: 4, sibsp: 3, parch: 2, fare: 27.9, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 65, name: "Stewart, Mr. Albert A", pclass: 1, sex: "male", age: 64, sibsp: 0, parch: 0, fare: 27.7208, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 66, name: "Moubarek, Master. Gerios", pclass: 3, sex: "male", age: 7, sibsp: 1, parch: 1, fare: 15.2458, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 67, name: "Nye, Mrs. (Elizabeth Ramell)", pclass: 2, sex: "female", age: 29, sibsp: 0, parch: 0, fare: 10.5, embarked: "S", cabin: "F33", deck: "F", survived: 1 },
  { id: 68, name: "Crease, Mr. Ernest James", pclass: 3, sex: "male", age: 19, sibsp: 0, parch: 0, fare: 8.1583, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 69, name: "Andersson, Miss. Erna Alexandra", pclass: 3, sex: "female", age: 17, sibsp: 4, parch: 2, fare: 7.925, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 70, name: "Kink, Mr. Vincenz", pclass: 3, sex: "male", age: 26, sibsp: 2, parch: 0, fare: 8.6625, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 71, name: "Jenkin, Mr. Stephen Curnow", pclass: 2, sex: "male", age: 32, sibsp: 0, parch: 0, fare: 10.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 72, name: "Goodwin, Miss. Lillian Amy", pclass: 3, sex: "female", age: 16, sibsp: 5, parch: 2, fare: 46.9, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 73, name: "Hood, Mr. Ambrose Jr", pclass: 2, sex: "male", age: 21, sibsp: 0, parch: 0, fare: 73.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 74, name: "Chronopoulos, Mr. Apostolos", pclass: 3, sex: "male", age: 26, sibsp: 1, parch: 0, fare: 14.4542, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 75, name: "Bing, Mr. Lee", pclass: 3, sex: "male", age: 32, sibsp: 0, parch: 0, fare: 56.4958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 76, name: "Moen, Mr. Sigurd Hansen", pclass: 3, sex: "male", age: 25, sibsp: 0, parch: 0, fare: 7.65, embarked: "S", cabin: "F G73", deck: "F", survived: 0 },
  { id: 77, name: "Staneff, Mr. Ivan", pclass: 3, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 78, name: "Moutal, Mr. Rahamin Haim", pclass: 3, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 79, name: "Caldwell, Master. Alden Gates", pclass: 2, sex: "male", age: 0.83, sibsp: 0, parch: 2, fare: 29, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 80, name: "Dowdell, Miss. Elizabeth", pclass: 3, sex: "female", age: 30, sibsp: 0, parch: 0, fare: 12.475, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 81, name: "Waelens, Mr. Achille", pclass: 3, sex: "male", age: 22, sibsp: 0, parch: 0, fare: 9, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 82, name: "Sheerlinck, Mr. Jan Baptist", pclass: 3, sex: "male", age: 29, sibsp: 0, parch: 0, fare: 9.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 83, name: "McDermott, Miss. Brigdet Delia", pclass: 3, sex: "female", age: 20, sibsp: 0, parch: 0, fare: 7.7875, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 84, name: "Carrau, Mr. Francisco M", pclass: 1, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 47.1, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 85, name: "Ilett, Miss. Bertha", pclass: 2, sex: "female", age: 17, sibsp: 0, parch: 0, fare: 10.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 86, name: "Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)", pclass: 3, sex: "female", age: 33, sibsp: 3, parch: 0, fare: 15.85, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 87, name: "Ford, Mr. William Neal", pclass: 3, sex: "male", age: 16, sibsp: 1, parch: 3, fare: 34.375, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 88, name: "Slocovski, Mr. Selman Francis", pclass: 3, sex: "male", age: 25, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 89, name: "Fortune, Miss. Mabel Helen", pclass: 1, sex: "female", age: 23, sibsp: 3, parch: 2, fare: 263, embarked: "S", cabin: "C23 C25 C27", deck: "C", survived: 1 },
  { id: 90, name: "Celotti, Mr. Francesco", pclass: 3, sex: "male", age: 24, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 91, name: "Christmann, Mr. Emil", pclass: 3, sex: "male", age: 29, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 92, name: "Andreasson, Mr. Paul Edvin", pclass: 3, sex: "male", age: 20, sibsp: 0, parch: 0, fare: 7.8542, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 93, name: "Chaffee, Mr. Herbert Fuller", pclass: 1, sex: "male", age: 46, sibsp: 1, parch: 0, fare: 61.175, embarked: "S", cabin: "E31", deck: "E", survived: 0 },
  { id: 94, name: "Dean, Mr. Bertram Frank", pclass: 3, sex: "male", age: 26, sibsp: 1, parch: 2, fare: 20.575, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 95, name: "Coxon, Mr. Daniel", pclass: 3, sex: "male", age: 59, sibsp: 0, parch: 0, fare: 7.25, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 96, name: "Shorney, Mr. Charles Joseph", pclass: 3, sex: "male", age: 27, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 97, name: "Goldschmidt, Mr. George B", pclass: 1, sex: "male", age: 71, sibsp: 0, parch: 0, fare: 34.6542, embarked: "C", cabin: "A5", deck: "A", survived: 0 },
  { id: 98, name: "Greenfield, Mr. William Bertram", pclass: 1, sex: "male", age: 23, sibsp: 0, parch: 1, fare: 63.3583, embarked: "C", cabin: "D10 D12", deck: "D", survived: 1 },
  { id: 99, name: "Doling, Mrs. John T (Ada Julia Bone)", pclass: 2, sex: "female", age: 34, sibsp: 0, parch: 1, fare: 23, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 100, name: "Kantor, Mr. Sinai", pclass: 2, sex: "male", age: 34, sibsp: 1, parch: 0, fare: 26, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 101, name: "Petranec, Miss. Matilda", pclass: 3, sex: "female", age: 28, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 102, name: "Petroff, Mr. Pastcho ('Nenkoff')", pclass: 3, sex: "male", age: 25, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 103, name: "White, Mr. Richard Frasar", pclass: 1, sex: "male", age: 21, sibsp: 0, parch: 1, fare: 77.2875, embarked: "S", cabin: "D26", deck: "D", survived: 0 },
  { id: 104, name: "Johansson, Mr. Gustaf Joel", pclass: 3, sex: "male", age: 33, sibsp: 0, parch: 0, fare: 8.6542, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 105, name: "Gustafsson, Mr. Anders Vilhelm", pclass: 3, sex: "male", age: 37, sibsp: 2, parch: 0, fare: 7.925, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 106, name: "Mionoff, Mr. Stoytcho", pclass: 3, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 107, name: "Salkjelsvik, Miss. Anna Kristine", pclass: 3, sex: "female", age: 21, sibsp: 0, parch: 0, fare: 7.65, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 108, name: "Moss, Mr. Albert Johan", pclass: 3, sex: "male", age: 29, sibsp: 0, parch: 0, fare: 7.775, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 109, name: "Rekic, Mr. Tido", pclass: 3, sex: "male", age: 38, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 110, name: "Moran, Miss. Bertha", pclass: 3, sex: "female", age: 28, sibsp: 1, parch: 0, fare: 24.15, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 111, name: "Porter, Mr. Walter Chamberlain", pclass: 1, sex: "male", age: 47, sibsp: 0, parch: 0, fare: 52, embarked: "S", cabin: "C110", deck: "C", survived: 0 },
  { id: 112, name: "Zabour, Miss. Hileni", pclass: 3, sex: "female", age: 14.5, sibsp: 1, parch: 0, fare: 14.4542, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 113, name: "Barton, Mr. David John", pclass: 3, sex: "male", age: 22, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 114, name: "Jussila, Miss. Katriina", pclass: 3, sex: "female", age: 20, sibsp: 1, parch: 0, fare: 9.825, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 115, name: "Attalah, Miss. Malake", pclass: 3, sex: "female", age: 17, sibsp: 0, parch: 0, fare: 14.4583, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 116, name: "Pekoniemi, Mr. Edvard", pclass: 3, sex: "male", age: 24, sibsp: 0, parch: 0, fare: 7.925, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 117, name: "Connors, Mr. Patrick", pclass: 3, sex: "male", age: 70.5, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 118, name: "Turpin, Mr. William John Robert", pclass: 2, sex: "male", age: 29, sibsp: 1, parch: 0, fare: 21, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 119, name: "Baxter, Mr. Quigg Edmond", pclass: 1, sex: "male", age: 24, sibsp: 0, parch: 1, fare: 247.5208, embarked: "C", cabin: "B58 B60", deck: "B", survived: 0 },
  { id: 120, name: "Andersson, Miss. Ellis Anna Maria", pclass: 3, sex: "female", age: 2, sibsp: 4, parch: 2, fare: 31.275, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 121, name: "Hickman, Mr. Stanley George", pclass: 2, sex: "male", age: 21, sibsp: 2, parch: 0, fare: 73.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 122, name: "Moore, Mr. Leonard Charles", pclass: 3, sex: "male", age: 23, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 123, name: "Nasser, Mr. Nicholas", pclass: 2, sex: "male", age: 32.5, sibsp: 1, parch: 0, fare: 30.0708, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 124, name: "Webber, Miss. Susan", pclass: 2, sex: "female", age: 32.5, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "E101", deck: "E", survived: 1 },
  { id: 125, name: "White, Mr. Percival Wayland", pclass: 1, sex: "male", age: 54, sibsp: 0, parch: 1, fare: 77.2875, embarked: "S", cabin: "D26", deck: "D", survived: 0 },
  { id: 126, name: "Nicola-Muff, Master. Elias", pclass: 3, sex: "male", age: 12, sibsp: 1, parch: 0, fare: 11.2417, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 127, name: "McMahon, Mr. Martin", pclass: 3, sex: "male", age: 26, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 128, name: "Madsen, Mr. Fridtjof Arne", pclass: 3, sex: "male", age: 24, sibsp: 0, parch: 0, fare: 7.1417, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 129, name: "Peter, Miss. Anna", pclass: 3, sex: "female", age: 2, sibsp: 1, parch: 1, fare: 22.3583, embarked: "C", cabin: "F E69", deck: "F", survived: 1 },
  { id: 130, name: "Ekstrom, Mr. Johan", pclass: 3, sex: "male", age: 45, sibsp: 0, parch: 0, fare: 6.975, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 131, name: "Drazenoic, Mr. Jozef", pclass: 3, sex: "male", age: 33, sibsp: 0, parch: 0, fare: 7.8958, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 132, name: "Coelho, Mr. Domingos Fernande", pclass: 3, sex: "male", age: 20, sibsp: 0, parch: 0, fare: 7.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 133, name: "Robins, Mrs. Alexander A (Grace Charlick)", pclass: 3, sex: "female", age: 47, sibsp: 1, parch: 0, fare: 14.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 134, name: "Weisz, Mrs. Leopold (Mathilde Francoise Pede)", pclass: 2, sex: "female", age: 29, sibsp: 1, parch: 0, fare: 26, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 135, name: "Sobey, Mr. Samuel James Hayden", pclass: 2, sex: "male", age: 25, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 136, name: "Richard, Mr. Emile", pclass: 2, sex: "male", age: 23, sibsp: 0, parch: 0, fare: 15.0458, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 137, name: "Newsom, Miss. Helen Monypeny", pclass: 1, sex: "female", age: 19, sibsp: 0, parch: 2, fare: 26.2833, embarked: "S", cabin: "D47", deck: "D", survived: 1 },
  { id: 138, name: "Futrelle, Mr. Jacques Heath", pclass: 1, sex: "male", age: 37, sibsp: 1, parch: 0, fare: 53.1, embarked: "S", cabin: "C123", deck: "C", survived: 0 },
  { id: 139, name: "Osen, Mr. Olaf Elon", pclass: 3, sex: "male", age: 16, sibsp: 0, parch: 0, fare: 9.2167, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 140, name: "Giglio, Mr. Victor", pclass: 1, sex: "male", age: 24, sibsp: 0, parch: 0, fare: 79.2, embarked: "C", cabin: "B86", deck: "B", survived: 0 },
  { id: 141, name: "Boulos, Mrs. Joseph (Sultana)", pclass: 3, sex: "female", age: 40, sibsp: 0, parch: 2, fare: 15.2458, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 142, name: "Nysten, Miss. Anna Sofia", pclass: 3, sex: "female", age: 22, sibsp: 0, parch: 0, fare: 7.75, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 143, name: "Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)", pclass: 3, sex: "female", age: 24, sibsp: 1, parch: 0, fare: 15.85, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 144, name: "Burke, Mr. Jeremiah", pclass: 3, sex: "male", age: 19, sibsp: 0, parch: 0, fare: 6.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 145, name: "Andrew, Mr. Edgardo Samuel", pclass: 2, sex: "male", age: 18, sibsp: 0, parch: 0, fare: 11.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 146, name: "Nicholls, Mr. Joseph Charles", pclass: 2, sex: "male", age: 19, sibsp: 1, parch: 1, fare: 36.75, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 147, name: "Andersson, Mr. August Edvard", pclass: 3, sex: "male", age: 27, sibsp: 0, parch: 0, fare: 7.7958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 148, name: "Ford, Miss. Robina Maggie", pclass: 3, sex: "female", age: 9, sibsp: 2, parch: 2, fare: 34.375, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 149, name: "Navratil, Mr. Michel ('Louis M Hoffman')", pclass: 2, sex: "male", age: 36.5, sibsp: 0, parch: 2, fare: 26, embarked: "S", cabin: "F2", deck: "F", survived: 0 },
  { id: 150, name: "Byllesby, Mr. Thomas Richard", pclass: 2, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 151, name: "Bateman, Rev. Robert James", pclass: 2, sex: "male", age: 51, sibsp: 0, parch: 0, fare: 12.525, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 152, name: "Pears, Mrs. Thomas (Edith Wearne)", pclass: 1, sex: "female", age: 22, sibsp: 1, parch: 0, fare: 66.6, embarked: "S", cabin: "C2", deck: "C", survived: 1 },
  { id: 153, name: "Meo, Mr. Alfonzo", pclass: 3, sex: "male", age: 55.5, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 154, name: "van Billiard, Mr. Austin Blyler", pclass: 3, sex: "male", age: 40.5, sibsp: 0, parch: 2, fare: 14.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 155, name: "Olsen, Mr. Ole Martin", pclass: 3, sex: "male", age: 27, sibsp: 0, parch: 0, fare: 7.3125, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 156, name: "Williams, Mr. Charles Duane", pclass: 1, sex: "male", age: 51, sibsp: 0, parch: 1, fare: 61.3792, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 157, name: "Gilnagh, Miss. Katie ('Mary')", pclass: 3, sex: "female", age: 16, sibsp: 0, parch: 0, fare: 7.7333, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 158, name: "Corn, Mr. Harry", pclass: 3, sex: "male", age: 30, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 159, name: "Smiljanic, Mr. Mile", pclass: 3, sex: "male", age: 30, sibsp: 0, parch: 0, fare: 8.6625, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 160, name: "Sage, Master. Thomas Henry", pclass: 3, sex: "male", age: 5, sibsp: 8, parch: 2, fare: 69.55, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 161, name: "Cribb, Mr. John Hatfield", pclass: 3, sex: "male", age: 44, sibsp: 0, parch: 1, fare: 16.1, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 162, name: "Watt, Mrs. James (Elizabeth 'Bessie' Inglis Milne)", pclass: 2, sex: "female", age: 40, sibsp: 0, parch: 0, fare: 15.75, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 163, name: "Bengtsson, Mr. John Viktor", pclass: 3, sex: "male", age: 26, sibsp: 0, parch: 0, fare: 7.775, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 164, name: "Calic, Mr. Jovo", pclass: 3, sex: "male", age: 17, sibsp: 0, parch: 0, fare: 8.6625, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 165, name: "Panula, Master. Eino Viljami", pclass: 3, sex: "male", age: 1, sibsp: 4, parch: 1, fare: 31.275, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 166, name: "Goldsmith, Master. Frank John William 'Frankie'", pclass: 3, sex: "male", age: 9, sibsp: 0, parch: 2, fare: 20.525, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 167, name: "Chibnall, Mrs. (Edith Martha Bowerman)", pclass: 1, sex: "female", age: 48, sibsp: 0, parch: 1, fare: 55, embarked: "S", cabin: "E33", deck: "E", survived: 1 },
  { id: 168, name: "Skoog, Mrs. William (Anna Bernhardina Karlsson)", pclass: 3, sex: "female", age: 45, sibsp: 1, parch: 4, fare: 27.9, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 169, name: "Baumann, Mr. John D", pclass: 1, sex: "male", age: 40, sibsp: 0, parch: 0, fare: 25.925, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 170, name: "Ling, Mr. Lee", pclass: 3, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 56.4958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 171, name: "Van der hoef, Mr. Wyckoff", pclass: 1, sex: "male", age: 61, sibsp: 0, parch: 0, fare: 33.5, embarked: "S", cabin: "B19", deck: "B", survived: 0 },
  { id: 172, name: "Rice, Master. Arthur", pclass: 3, sex: "male", age: 4, sibsp: 4, parch: 1, fare: 29.125, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 173, name: "Johnson, Miss. Eleanor Ileen", pclass: 3, sex: "female", age: 1, sibsp: 1, parch: 1, fare: 11.1333, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 174, name: "Sivola, Mr. Antti Gustaf", pclass: 3, sex: "male", age: 21, sibsp: 0, parch: 0, fare: 7.925, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 175, name: "Smith, Mr. James Clinch", pclass: 1, sex: "male", age: 56, sibsp: 0, parch: 0, fare: 30.6958, embarked: "C", cabin: "A7", deck: "A", survived: 0 },
  { id: 176, name: "Klasen, Mr. Klas Albin", pclass: 3, sex: "male", age: 18, sibsp: 1, parch: 1, fare: 7.8542, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 177, name: "Lefebre, Master. Henry Forbes", pclass: 3, sex: "male", age: 5, sibsp: 3, parch: 1, fare: 25.4667, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 178, name: "Isham, Miss. Ann Elizabeth", pclass: 1, sex: "female", age: 50, sibsp: 0, parch: 0, fare: 28.7125, embarked: "C", cabin: "C49", deck: "C", survived: 0 },
  { id: 179, name: "Hale, Mr. Reginald", pclass: 2, sex: "male", age: 30, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 180, name: "Leonard, Mr. Lionel", pclass: 3, sex: "male", age: 36, sibsp: 0, parch: 0, fare: 0, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 181, name: "Sage, Miss. Constance Gladys", pclass: 3, sex: "female", age: 13, sibsp: 8, parch: 2, fare: 69.55, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 182, name: "Pernot, Mr. Rene", pclass: 2, sex: "male", age: 33, sibsp: 0, parch: 0, fare: 15.05, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 183, name: "Asplund, Master. Clarence Gustaf Hugo", pclass: 3, sex: "male", age: 9, sibsp: 4, parch: 2, fare: 31.3875, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 184, name: "Becker, Master. Richard F", pclass: 2, sex: "male", age: 1, sibsp: 2, parch: 1, fare: 39, embarked: "S", cabin: "F4", deck: "F", survived: 1 },
  { id: 185, name: "Kink-Heilmann, Miss. Luise Gretchen", pclass: 3, sex: "female", age: 4, sibsp: 0, parch: 2, fare: 22.025, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 186, name: "Rood, Mr. Hugh Roscoe", pclass: 1, sex: "male", age: 39, sibsp: 0, parch: 0, fare: 50, embarked: "S", cabin: "A32", deck: "A", survived: 0 },
  { id: 187, name: "O'Brien, Mrs. Thomas (Johanna 'Hannah' Godfrey)", pclass: 3, sex: "female", age: 26, sibsp: 1, parch: 0, fare: 15.5, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 188, name: "Romaine, Mr. Charles Hallace ('Mr C Rolmane')", pclass: 1, sex: "male", age: 45, sibsp: 0, parch: 0, fare: 26.55, embarked: "S", cabin: "E50", deck: "E", survived: 1 },
  { id: 189, name: "Bourke, Mr. John", pclass: 3, sex: "male", age: 40, sibsp: 1, parch: 1, fare: 15.5, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 190, name: "Turcin, Mr. Stjepan", pclass: 3, sex: "male", age: 36, sibsp: 0, parch: 0, fare: 7.8958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 191, name: "Pinsky, Mrs. (Rosa)", pclass: 2, sex: "female", age: 32, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 192, name: "Carbines, Mr. William", pclass: 2, sex: "male", age: 19, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 193, name: "Andersen-Jensen, Miss. Carla Christine Nielsine", pclass: 3, sex: "female", age: 19, sibsp: 0, parch: 0, fare: 7.8542, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 194, name: "Navratil, Master. Michel M", pclass: 2, sex: "male", age: 3, sibsp: 1, parch: 1, fare: 26, embarked: "S", cabin: "F2", deck: "F", survived: 1 },
  { id: 195, name: "Brown, Mrs. James Joseph (Margaret Tobin - Unsinkable Molly Brown)", pclass: 1, sex: "female", age: 44, sibsp: 0, parch: 0, fare: 27.7208, embarked: "C", cabin: "B4", deck: "B", survived: 1 },
  { id: 196, name: "Lurette, Miss. Elise", pclass: 1, sex: "female", age: 58, sibsp: 0, parch: 0, fare: 146.5208, embarked: "C", cabin: "B80", deck: "B", survived: 1 },
  { id: 197, name: "Mernelson, Mr. Mernest", pclass: 3, sex: "male", age: 24, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 198, name: "Olsen, Mr. Karl Siegwart Andreas", pclass: 3, sex: "male", age: 42, sibsp: 0, parch: 1, fare: 8.4042, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 199, name: "Madigan, Miss. Margaret 'Maggie'", pclass: 3, sex: "female", age: 21, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 200, name: "Yrois, Miss. Henriette ('Mrs Harbeck')", pclass: 2, sex: "female", age: 24, sibsp: 0, parch: 0, fare: 13, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 201, name: "Vande Walle, Mr. Nestor Cyriel", pclass: 3, sex: "male", age: 28, sibsp: 0, parch: 0, fare: 9.5, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 202, name: "Sage, Mr. Frederick", pclass: 3, sex: "male", age: 17, sibsp: 8, parch: 2, fare: 69.55, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 203, name: "Johanson, Mr. Jakob Alfred", pclass: 3, sex: "male", age: 34, sibsp: 0, parch: 0, fare: 6.4958, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 204, name: "Youseff, Mr. Gerious", pclass: 3, sex: "male", age: 45.5, sibsp: 0, parch: 0, fare: 7.225, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 205, name: "Cohen, Mr. Gurshon 'Gus'", pclass: 3, sex: "male", age: 18, sibsp: 0, parch: 0, fare: 8.05, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 206, name: "Strom, Miss. Telma Matilda", pclass: 3, sex: "female", age: 2, sibsp: 0, parch: 1, fare: 10.4625, embarked: "S", cabin: "G6", deck: "G", survived: 0 },
  { id: 207, name: "Backstrom, Mr. Karl Alfred", pclass: 3, sex: "male", age: 32, sibsp: 1, parch: 0, fare: 15.85, embarked: "S", cabin: "Unknown", deck: "Unknown", survived: 0 },
  { id: 208, name: "Albimona, Mr. Nassef Cassem", pclass: 3, sex: "male", age: 26, sibsp: 0, parch: 0, fare: 18.7875, embarked: "C", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 209, name: "Carr, Miss. Helen 'Ellen'", pclass: 3, sex: "female", age: 16, sibsp: 0, parch: 0, fare: 7.75, embarked: "Q", cabin: "Unknown", deck: "Unknown", survived: 1 },
  { id: 210, name: "Blank, Mr. Henry", pclass: 1, sex: "male", age: 40, sibsp: 0, parch: 0, fare: 31, embarked: "C", cabin: "A31", deck: "A", survived: 1 }
];

// Helper to get deck from cabin
function getDeck(cabin) {
  if (!cabin || cabin === "Unknown") return "Unknown";
  return cabin.charAt(0);
}

// Summary Statistics Calculator
function calculateDatasetSummary(dataset = TITANIC_DATASET) {
  const total = dataset.length;
  const survivedCount = dataset.filter(p => p.survived === 1).length;
  const diedCount = total - survivedCount;
  const survivalRate = (survivedCount / total) * 100;

  const femaleCount = dataset.filter(p => p.sex === "female").length;
  const femaleSurvived = dataset.filter(p => p.sex === "female" && p.survived === 1).length;
  const femaleSurvivalRate = femaleCount ? (femaleSurvived / femaleCount) * 100 : 0;

  const maleCount = dataset.filter(p => p.sex === "male").length;
  const maleSurvived = dataset.filter(p => p.sex === "male" && p.survived === 1).length;
  const maleSurvivalRate = maleCount ? (maleSurvived / maleCount) * 100 : 0;

  const pclass1 = dataset.filter(p => p.pclass === 1);
  const pclass1Rate = (pclass1.filter(p => p.survived === 1).length / pclass1.length) * 100;

  const pclass2 = dataset.filter(p => p.pclass === 2);
  const pclass2Rate = (pclass2.filter(p => p.survived === 1).length / pclass2.length) * 100;

  const pclass3 = dataset.filter(p => p.pclass === 3);
  const pclass3Rate = (pclass3.filter(p => p.survived === 1).length / pclass3.length) * 100;

  const children = dataset.filter(p => p.age < 16);
  const childrenRate = children.length ? (children.filter(p => p.survived === 1).length / children.length) * 100 : 0;

  return {
    total,
    survivedCount,
    diedCount,
    survivalRate: survivalRate.toFixed(1),
    femaleCount,
    femaleSurvivalRate: femaleSurvivalRate.toFixed(1),
    maleCount,
    maleSurvivalRate: maleSurvivalRate.toFixed(1),
    pclass1Rate: pclass1Rate.toFixed(1),
    pclass2Rate: pclass2Rate.toFixed(1),
    pclass3Rate: pclass3Rate.toFixed(1),
    childrenCount: children.length,
    childrenRate: childrenRate.toFixed(1)
  };
}
